myproject/myproject/urls.py
"""todoproject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vehicle_management.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myproject/vehicle_management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    SuperAdminVehicleListView,
    SuperAdminVehicleDetailView,
    SuperAdminVehicleCreateView,
    SuperAdminVehicleUpdateView,
    SuperAdminVehicleDeleteView,
    AdminVehicleListView,
    AdminVehicleDetailView,
    AdminVehicleUpdateView,
    UserVehicleListView, VehicleHomeView,
)
from django.contrib.auth.decorators import login_required
from vehicle_management.views import ProfileView

app_name = 'vehicle_management'

urlpatterns = [
    path('', VehicleHomeView.as_view(), name='home'),
    path('superadmin/vehicle/list/', SuperAdminVehicleListView.as_view(), name='superadmin_vehicle_list'),
    path('superadmin/vehicle/<int:pk>/', SuperAdminVehicleDetailView.as_view(), name='superadmin_vehicle_detail'),
    path('superadmin/vehicle/create/', SuperAdminVehicleCreateView.as_view(), name='superadmin_vehicle_create'),
    path('superadmin/vehicle/<int:pk>/update/', SuperAdminVehicleUpdateView.as_view(), name='superadmin_vehicle_update'),
    path('superadmin/vehicle/<int:pk>/delete/', SuperAdminVehicleDeleteView.as_view(), name='superadmin_vehicle_delete'),
    path('admin/vehicle/list/', AdminVehicleListView.as_view(), name='admin_vehicle_list'),
    path('admin/vehicle/<int:pk>/', AdminVehicleDetailView.as_view(), name='admin_vehicle_detail'),
    path('admin/vehicle/<int:pk>/update/', AdminVehicleUpdateView.as_view(), name='admin_vehicle_update'),
    path('user/vehicle/list/', UserVehicleListView.as_view(), name='user_vehicle_list'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('accounts/profile/', login_required(ProfileView.as_view()), name='profile'),
]

myproject/vehicle_management/models.py
from django.db import models

class Vehicle(models.Model):
    VEHICLE_TYPE = (
        ('2', 'Two Wheeler'),
        ('3', 'Three Wheeler'),
        ('4', 'Four Wheeler')
    )

    vehicle_number = models.CharField(max_length=20, unique=True)
    vehicle_type = models.CharField(max_length=1, choices=VEHICLE_TYPE)
    vehicle_model = models.CharField(max_length=50)
    vehicle_description = models.TextField()

    def __str__(self):
        return self.vehicle_number

myproject/vehicle_management/forms.py
from django import forms
from .models import Vehicle

class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ['vehicle_number', 'vehicle_type', 'vehicle_model', 'vehicle_description']
        widgets = {
            'vehicle_description': forms.Textarea(attrs={'rows': 5})
        }

myproject/vehicle_management/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .models import Vehicle
from .forms import VehicleForm
from django.views.generic.base import TemplateView


# SuperAdmin View

class VehicleHomeView(ListView):
    model = Vehicle
    context_object_name = 'home'
    template_name = 'home.html'


class SuperAdminVehicleListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Vehicle
    template_name = 'vehicle_list.html'
    context_object_name = 'vehicles'
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_superuser


class SuperAdminVehicleDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Vehicle
    template_name = 'vehicle_detail.html'
    context_object_name = 'vehicle'
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_superuser


class SuperAdminVehicleCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Vehicle
    form_class = VehicleForm
    template_name = 'vehicle_form.html'
    success_url = reverse_lazy('vehicle_management:superadmin_vehicle_list')
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_superuser


class SuperAdminVehicleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Vehicle
    form_class = VehicleForm
    template_name = 'vehicle_form.html'
    success_url = reverse_lazy('vehicle_management:superadmin_vehicle_list')
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_superuser


class SuperAdminVehicleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Vehicle
    template_name = 'vehicle_confirm_delete.html'
    success_url = reverse_lazy('vehicle_management:superadmin_vehicle_list')
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_superuser


# Admin View
class AdminVehicleListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Vehicle
    template_name = 'vehicle_list.html'
    context_object_name = 'vehicles'
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_staff


class AdminVehicleDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Vehicle
    template_name = 'vehicle_detail.html'
    context_object_name = 'vehicle'
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_staff


class AdminVehicleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Vehicle
    form_class = VehicleForm
    template_name = 'vehicle_management/vehicle_form.html'
    success_url = reverse_lazy('vehicle_management:admin_vehicle_list')
    login_url = 'login'

    def test_func(self):
        return self.request.user.is_staff


# User View
class UserVehicleListView(LoginRequiredMixin, ListView):
    model = Vehicle
    template_name = 'vehicle_management/vehicle_list.html'
    context_object_name = 'vehicles'
    login_url = 'login'

    def get_queryset(self):
        return Vehicle.objects.all().order_by('vehicle_number')


class ProfileView(TemplateView):
    template_name = 'profile.html'

myproject/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Vehicle Management{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-NfCtPnmruGxEv5p3PyUEZWe30pZ1wpqlJi9X9weQFFy1RnIrY/FYtP+wzVVQJxN72ovR0W0N8T/gT9MIvxCGhA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'vehicle_management:home' %}">Vehicle Management</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
           <li class="nav-item">
                <a class="nav-link" href="{% url 'vehicle_management:superadmin_vehicle_list' %}">Vehicle List</a>
            </li>
            {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehicle_management:superadmin_vehicle_create' %}">Create Vehicle</a>
              </li>
  {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vehicle_management:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vehicle_management:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container my-4">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

myproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 mt-3">
        <p class="text-center">Welcome to my Vehicle Management System! This system is designed to help you manage your vehicles more efficiently.</p>
        <p class="text-center">NOTE: **Please go to Admin Panel and create user**</p>
        <center><a href="{% url 'vehicle_management:login' %}" class="btn btn-primary">Login</a></center>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <center><img src="{% static 'img/background.png' %}" class="img-fluid banner-img" alt="Banner Image"></center>
      </div>
    </div>
  </div>
<footer>
<div class="mt-auto">
  <p class="text-center">&copy;ABC TECH PVT. LTD. All Rights Reserved</p>
</div>
  </footer>
{% endblock %}

myproject/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 mt-5">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title text-center">Login Form</h2>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary d-block mx-auto mt-3">Login </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myproject/templates/logout.html
{% extends 'base.html' %}

{% block content %}
   <center> <h1>Logged out successfully!</h1>
    <p>Thank you for using our website. Click <a href="{% url 'vehicle_management:home' %}">here</a> to return to the homepage.</p></center>
{% endblock %}

myproject/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<center>    <h1>LOGIN COMPLETED</h1>
    <p>Welcome, {{ request.user.username }}!</p>
    <p>Now Create Vehicle List</p>
                <a class="nav-link" href="{% url 'vehicle_management:superadmin_vehicle_create' %}">Create Vehicle</a></center>
<center><a href="{% url 'vehicle_management:superadmin_vehicle_list' %}">Vehicle List</a></button></center>
{% endblock %}

myproject/templates/vehicle_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h2>Delete Vehicle</h2>
  <p>Are you sure you want to delete "{{ vehicle.make }} {{ vehicle.model }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a href="{% url 'vehicle_management:superadmin_vehicle_detail' pk=vehicle.pk %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

myproject/templates/vehicle_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>Vehicle Detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <th>Vehicle Number:</th>
        <td>{{ object.vehicle_number }}</td>
      </tr>
      <tr>
        <th>Vehicle Type:</th>
        <td>{{ object.vehicle_type }}</td>
      </tr>
      <tr>
        <th>Vehicle Model:</th>
        <td>{{ object.vehicle_model }}</td>
      </tr>
      <tr>
        <th>Vehicle Description:</th>
        <td>{{ object.vehicle_description }}</td>
      </tr>
    </tbody>
  </table>
  {% if request.user.is_superuser %}
    <p><a href="{% url 'vehicle_management:superadmin_vehicle_update' object.pk %}">Update</a></p>
  {% endif %}
{% endblock %}

myproject/templates/vehicle_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6 mt-3">
        <div class="card">
          <div class="card-body">
         <center> <h2 class="card-title">{% if vehicle %}Update{% else %}Create{% endif %} Vehicle</center>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
             <center> <button type="submit" class="btn btn-primary">{% if vehicle %}Update{% else %}Create{% endif %}</button></center>
                <br>
             <center><button type="submit"><a href="{% url 'vehicle_management:superadmin_vehicle_list' %}">Vehicle List</a></button></center>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

myproject/templates/vehicle_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Vehicle List</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Vehicle Number</th>
        <th>Vehicle Type</th>
        <th>Vehicle Model</th>
        <th>Vehicle Description</th>
        {% if request.user.is_staff %}
          <th>Actions</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for vehicle in object_list %}
        <tr>
          <td>{{ vehicle.vehicle_number }}</td>
          <td>{{ vehicle.vehicle_type }}</td>
          <td>{{ vehicle.vehicle_model }}</td>
          <td>{{ vehicle.vehicle_description }}</td>
          {% if request.user.is_staff %}
            <td>
              {% if request.user.is_superuser %}
                <a href="{% url 'vehicle_management:superadmin_vehicle_detail' vehicle.pk %}">Detail</a> |
                <a href="{% url 'vehicle_management:superadmin_vehicle_update' vehicle.pk %}">Update</a> |
                <a href="{% url 'vehicle_management:superadmin_vehicle_delete' vehicle.pk %}">Delete</a>
              {% else %}
                <a href="{% url 'vehicle_management:admin_vehicle_detail' vehicle.pk %}">Detail</a> |
                <a href="{% url 'vehicle_management:admin_vehicle_update' vehicle.pk %}">Update</a>
              {% endif %}
            </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}